export const interviewData = [
  {
    id: 1,
    userid: 123,
    username: "John Doe",
    timedate: "2023-09-16T10:30:00Z",
    title: "Interview with Cohesity for Senior Security Software Engineer",
    tags: ["React", "Next", "Javascript"],
    category: "Frontend Development",
    description:
      "I applied for that role in Linkedin and got a call from HR 1st round: Call with recruiter to ask about my experience and expectations.2nd round: With Hiring manager - Typical behavioral interview questions and some technical questions.Then I received a call from Recruiter to schedule all 3 interviews in a week. 3rd round: Domain interview deep into technical questions related to Security and Software engineering.4th round: Security System Design interview - It was more fun.So now, after the 4th round I was waiting for the 5th round to happen but all of a sudden, the recruiter calls me to inform that the 5th round has been canceled. I asked her why but she did not give me any straight answers to that and she said that she is unaware why the 5th round has to be canceled but she was informed by another recruiter that it needs to be canceled and that's all. She also mentioned that she will get back to me.So what does it mean? Could anyone please tell me? This is giving me a very bad feeling that they will not conduct the 5th round though they scheduled all last 3 rounds at once. Has this happened to anyone while interviewing with any other company?",
    imageURL: "https://example.com/image1.jpg",
    slug: "interview-with-cohesity-for-senior-security-software-engineer",
  },
  {
    id: 2,
    userid: 124,
    username: "Jane Smith",
    timedate: "2023-09-16T11:00:00Z",
    title: "Interview with XYZ Company for Backend Developer",
    tags: ["Node.js", "Express", "MongoDB"],
    category: "Backend Development",
    description: `Explanation:
    This component is a functional component named UserComment.
    It accepts username, comment, and timestamp as props.
    The component returns a div with a white background, padding, rounded corners, and a shadow using Tailwind CSS classes.
    Inside the div, there's a flex container (flex) with some margin at the bottom (mb-2).
    Inside the flex container, there's an image element (img) for the user avatar. It has a rounded border using the rounded-full class and a specified height and width (h-8 w-8).
    Next to the avatar, there's a div containing the username and timestamp information. The username is displayed with a bold font using font-semibold. The timestamp is displayed in gray using text-gray-500 and with a smaller font size (text-sm).
    Below the user information, there's another div displaying the comment text in a default color (text-gray-800).
    To use this UserComment component, you can import it into your React application and pass the necessary props (username, comment, and timestamp). Remember to replace the placeholder image URL (https://example.com/user-avatar.jpg) with the actual source of the user's avatar.`,
    imageURL: "https://example.com/image2.jpg",
    slug: "interview-with-xyz-company-for-backend-developer",
  },
  {
    id: 3,
    userid: 125,
    username: "Bob Johnson",
    timedate: "2023-09-16T11:30:00Z",
    title: "Interview with ABC Corporation for Data Analyst",
    tags: ["SQL", "Excel", "Data Analysis"],
    category: "Data Science",
    description: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.`,
    imageURL: "https://example.com/image3.jpg",
    slug: "interview-with-abc-corporation-for-data-analyst",
  },
  {
    id: 4,
    userid: 126,
    username: "Sarah Davis",
    timedate: "2023-09-16T12:00:00Z",
    title: "Interview with PQR Tech for UX/UI Designer",
    tags: ["Adobe XD", "Sketch", "Wireframing"],
    category: "Design",
    description: `Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.`,
    imageURL: "https://example.com/image4.jpg",
    slug: "interview-with-pqr-tech-for-ux-ui-designer",
  },
  {
    id: 5,
    userid: 127,
    username: "Michael Chang",
    timedate: "2023-09-16T12:30:00Z",
    title: "Interview with EFG Solutions for Data Engineer",
    tags: ["Python", "SQL", "Big Data"],
    category: "Other",
    description: `Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.`,
    imageURL: "https://example.com/image5.jpg",
    slug: "interview-with-efg-solutions-for-data-engineer",
  },
  {
    id: 6,
    userid: 128,
    username: "Emily Davis",
    timedate: "2023-09-16T13:00:00Z",
    title: "Interview with LMN Agency for Marketing Manager",
    tags: ["Digital Marketing", "SEO", "Social Media"],
    category: "Marketing",
    description: `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.`,
    imageURL: "https://example.com/image6.jpg",
    slug: "interview-with-lmn-agency-for-marketing-manager",
  },
  {
    id: 7,
    userid: 129,
    username: "Daniel Kim",
    timedate: "2023-09-16T13:30:00Z",
    title: "Interview with RST Innovations for AI Researcher",
    tags: ["Machine Learning", "Python", "Deep Learning"],
    category: "Artificial Intelligence",
    description: `Et harum quidem rerum facilis est et expedita distinctio.`,
    imageURL: "https://example.com/image7.jpg",
    slug: "interview-with-rst-innovations-for-ai-researcher",
  },
  {
    id: 8,
    userid: 130,
    username: "Olivia Martinez",
    timedate: "2023-09-16T14:00:00Z",
    title: "Interview with UVW Corporation for Product Manager",
    tags: ["Product Strategy", "Market Research", "Product Development"],
    category: "Product Management",
    description: `Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat.`,
    imageURL: "https://example.com/image8.jpg",
    slug: "interview-with-uvw-corporation-for-product-manager",
  },
  {
    id: 9,
    userid: 131,
    username: "Ethan Williams",
    timedate: "2023-09-16T14:30:00Z",
    title: "Interview with GHI Ventures for Financial Analyst",
    tags: ["Financial Modeling", "Excel", "Investment Analysis"],
    category: "Finance",
    description: `Omnis voluptas assumenda est, omnis dolor repellendus.`,
    imageURL: "https://example.com/image9.jpg",
    slug: "interview-with-ghi-ventures-for-financial-analyst",
  },
  {
    id: 10,
    userid: 132,
    username: "Ava Johnson",
    timedate: "2023-09-16T15:00:00Z",
    title: "Interview with XYZ Tech for DevOps Engineer",
    tags: ["Docker", "Kubernetes", "CI/CD"],
    category: "DevOps",
    description: `Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.`,
    imageURL: "https://example.com/image10.jpg",
    slug: "interview-with-xyz-tech-for-devops-engineer",
  },
];
